name: pipeline_tests

on: push

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11.3]

    name: UnitaryTests
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          - python -m pip install pytest .
          - python -m pip install pandas
          - python -m pip install numpy
          - python -m pip install pickle
          - python -m pip install os

      - name: Run tests
        run: pytest
